version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: serverMsg
    volumes:
      - ./database/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "0.0.0.0:27017-27019:27017-27019"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8008:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ROOT_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "4321:8080"
    volumes:
      - ./app:/home/node/app
      - ./app/node_modules:/home/node/app/node_modules
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon ./app/serverMsg.js

